export const dataForRpkiAnalysis = {
  ports: {
    incoming: {
      3323: "RTR, which caters to BGP clients",
      8323: "HTTP, which caters to user access",
      9556: "HTTP, which cater to exporter usage",
    },
  },
  dependencies: [
    {
      os: "ubuntu",
      softwares: [
        [
          "passwd",
          "cpe:2.3:a:shadow-utils:passwd:4.8:*:*:*:*:*:*:*",
          "rsync",
          "cpe:2.3:a:samba:rsync:3.1.3:*:*:*:*:*:*:*",
          "libssl-dev",
          "cpe:2.3:a:openssl:libssl-dev:1.1.1:*:*:*:*:*:*:*",
          "gcc",
          "cpe:2.3:a:gnu:gcc:9.3.0:*:*:*:*:*:*:*",
          "make",
          "cpe:2.3:a:gnu:make:4.2.1:*:*:*:*:*:*:*",
          "systemd",
          "cpe:2.3:a:freedesktop:systemd:245:*:*:*:*:*:*:*",
        ],
        [
          "passwd",
          "cpe:2.3:a:shadow-utils:passwd:4.8:*:*:*:*:*:*:*",
          "rsync",
          "cpe:2.3:a:samba:rsync:3.2.3:*:*:*:*:*:*:*",
          "libssl-dev",
          "cpe:2.3:a:openssl:libssl-dev:3.0.0:*:*:*:*:*:*:*",
          "gcc",
          "cpe:2.3:a:gnu:gcc:11.2.0:*:*:*:*:*:*:*",
          "make",
          "cpe:2.3:a:gnu:make:4.3:*:*:*:*:*:*:*",
          "systemd",
          "cpe:2.3:a:freedesktop:systemd:247:*:*:*:*:*:*:*",
        ],
      ],
    },
    {
      os: "entreprise",
      softwares: [
        [
          "shadow-utils",
          "cpe:2.3:a:shadow-maint:shadow-utils:4.6:*:*:*:*:*:*:*",
          "rsync",
          "cpe:2.3:a:samba:rsync:3.1.2:*:*:*:*:*:*:*",
          "openssl-devel",
          "cpe:2.3:a:openssl:openssl:1.1.1:*:*:*:*:*:*:*",
          "gcc",
          "cpe:2.3:a:gnu:gcc:8.3.1:*:*:*:*:*:*:*",
          "make",
          "cpe:2.3:a:gnu:make:4.2.1:*:*:*:*:*:*:*",
          "systemd",
          "cpe:2.3:a:freedesktop:systemd:239:*:*:*:*:*:*:*",
        ],
        [
          "shadow-utils",
          "cpe:2.3:a:shadow-maint:shadow-utils:4.8:*:*:*:*:*:*:*",
          "rsync",
          "cpe:2.3:a:samba:rsync:3.2.3:*:*:*:*:*:*:*",
          "openssl-devel",
          "cpe:2.3:a:openssl:openssl:3.0.0:*:*:*:*:*:*:*",
          "gcc",
          "cpe:2.3:a:gnu:gcc:11.2.0:*:*:*:*:*:*:*",
          "make",
          "cpe:2.3:a:gnu:make:4.3:*:*:*:*:*:*:*",
          "systemd",
          "cpe:2.3:a:freedesktop:systemd:247:*:*:*:*:*:*:*",
        ],
      ],
    },
    {
      os: "debian",
      softwares: [
        [
          "passwd",
          "cpe:2.3:a:shadow-utils:passwd:4.7:*:*:*:*:*:*:*",
          "rsync",
          "cpe:2.3:a:samba:rsync:3.1.3:*:*:*:*:*:*:*",
          "libssl-dev",
          "cpe:2.3:a:openssl:libssl-dev:1.1.1:*:*:*:*:*:*:*",
          "gcc",
          "cpe:2.3:a:gnu:gcc:8.3.0:*:*:*:*:*:*:*",
          "make",
          "cpe:2.3:a:gnu:make:4.2.1:*:*:*:*:*:*:*",
          "systemd",
          "cpe:2.3:a:freedesktop:systemd:245:*:*:*:*:*:*:*",
        ],
        [
          "passwd",
          "cpe:2.3:a:shadow-utils:passwd:4.8:*:*:*:*:*:*:*",
          "rsync",
          "cpe:2.3:a:samba:rsync:3.2.3:*:*:*:*:*:*:*",
          "libssl-dev",
          "cpe:2.3:a:openssl:libssl-dev:3.0.0:*:*:*:*:*:*:*",
          "gcc",
          "cpe:2.3:a:gnu:gcc:10.2.1:*:*:*:*:*:*:*",
          "make",
          "cpe:2.3:a:gnu:make:4.3:*:*:*:*:*:*:*",
          "systemd",
          "cpe:2.3:a:freedesktop:systemd:247:*:*:*:*:*:*:*",
        ],
      ],
    },
  ],
};
